"""
Unit tests for services.summarizer.
"""

from unittest.mock import MagicMock, patch

from providers.base_provider import AIProvider
from services.summarizer import summarize_news
from tests.types import ArticleFactory


def test_summarize_news_returns_summary(
    article_factory: ArticleFactory,
) -> None:
    """
    Returns the summary generated by the provider.
    """
    article = article_factory()

    provider: MagicMock = MagicMock(spec=AIProvider)
    provider.summarize.return_value = "AI Summary"

    result = summarize_news([article], provider)

    assert result == "AI Summary"
    provider.summarize.assert_called_once_with([article])


def test_summarize_news_empty_news() -> None:
    """
    Returns the default message when there are no news articles.
    """
    provider: MagicMock = MagicMock(spec=AIProvider)

    result = summarize_news([], provider)

    assert result == "No news articles available."
    provider.summarize.assert_not_called()


def test_summarize_news_calls_provider_once(
    article_factory: ArticleFactory,
) -> None:
    """
    Calls the provider exactly once.
    """
    article = article_factory()

    provider: MagicMock = MagicMock(spec=AIProvider)
    provider.summarize.return_value = "Summary"

    summarize_news([article], provider)

    provider.summarize.assert_called_once_with([article])


def test_summarize_news_handles_provider_exception(
    article_factory: ArticleFactory,
) -> None:
    """
    Returns a fallback message when the provider fails.
    """
    article = article_factory()

    provider: MagicMock = MagicMock(spec=AIProvider)
    provider.summarize.side_effect = RuntimeError("API failed")

    result = summarize_news([article], provider)

    assert result == "Unable to generate AI summary."


def test_summarize_news_logs_info(
    article_factory: ArticleFactory,
) -> None:
    """
    Logs informational messages during summarization.
    """
    article = article_factory()

    provider: MagicMock = MagicMock(spec=AIProvider)
    provider.summarize.return_value = "Summary"

    with patch("services.summarizer.logger.info") as mock_info:
        summarize_news([article], provider)

    assert mock_info.call_count == 2

    mock_info.assert_any_call(
        "Summarizing %d articles using %s.",
        1,
        provider.__class__.__name__,
    )

    mock_info.assert_any_call("News summarization completed.")


def test_summarize_news_logs_warning_for_empty_news() -> None:
    """
    Logs a warning when no news articles are supplied.
    """
    provider: MagicMock = MagicMock(spec=AIProvider)

    with patch("services.summarizer.logger.warning") as mock_warning:
        summarize_news([], provider)

    mock_warning.assert_called_once_with(
        "No news articles available for summarization."
    )
