"""
Unit tests for services.summarizer.
"""

from unittest.mock import Mock, patch

from services.summarizer import summarize_news
from tests.types import ArticleFactory


def test_summarize_news_empty_news() -> None:
    """
    Returns a default message when no news articles are available.
    """
    result = summarize_news([])

    assert result == "No news articles available."


def test_summarize_news_logs_warning_for_empty_news() -> None:
    """
    Logs a warning when no news articles are available.
    """
    with patch("services.summarizer.logger.warning") as mock_warning:
        summarize_news([])

    mock_warning.assert_called_once_with(
        "No news articles available for summarization."
    )


def test_summarize_news_calls_provider(
    article_factory: ArticleFactory,
) -> None:
    """
    Uses the configured provider to summarize news.
    """
    news = [
        article_factory(
            title="GPT-5 Released",
        )
    ]

    provider = Mock()
    provider.summarize.return_value = "AI Summary"

    with patch(
        "services.summarizer.ProviderFactory.get_provider",
        return_value=provider,
    ):
        result = summarize_news(news)

    provider.summarize.assert_called_once_with(news)
    assert result == "AI Summary"


def test_summarize_news_returns_provider_summary(
    article_factory: ArticleFactory,
) -> None:
    """
    Returns the summary generated by the provider.
    """
    news = [
        article_factory(
            title="Gemini 3 Released",
        )
    ]

    provider = Mock()
    provider.summarize.return_value = "Generated Summary"

    with patch(
        "services.summarizer.ProviderFactory.get_provider",
        return_value=provider,
    ):
        result = summarize_news(news)

    assert result == "Generated Summary"


def test_summarize_news_logs_completion(
    article_factory: ArticleFactory,
) -> None:
    """
    Logs completion after successful summarization.
    """
    news = [article_factory()]

    provider = Mock()
    provider.summarize.return_value = "Summary"

    with (
        patch(
            "services.summarizer.ProviderFactory.get_provider",
            return_value=provider,
        ),
        patch("services.summarizer.logger.info") as mock_info,
    ):
        summarize_news(news)

    mock_info.assert_any_call("News summarization completed.")


def test_summarize_news_returns_fallback_on_provider_exception(
    article_factory: ArticleFactory,
) -> None:
    """
    Returns a fallback message when the provider fails.
    """
    news = [article_factory()]

    provider = Mock()
    provider.summarize.side_effect = RuntimeError("Provider failed")

    with patch(
        "services.summarizer.ProviderFactory.get_provider",
        return_value=provider,
    ):
        result = summarize_news(news)

    assert result == "Unable to generate AI summary."


def test_summarize_news_logs_exception(
    article_factory: ArticleFactory,
) -> None:
    """
    Logs an exception when summarization fails.
    """
    news = [article_factory()]

    provider = Mock()
    provider.summarize.side_effect = RuntimeError()

    with (
        patch(
            "services.summarizer.ProviderFactory.get_provider",
            return_value=provider,
        ),
        patch("services.summarizer.logger.exception") as mock_exception,
    ):
        summarize_news(news)

    mock_exception.assert_called_once_with("News summarization failed.")
